[project]
name = 'certifikurs'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.certificate-data]
path = 'contracts/certificate-data.clar'
clarity_version = 3
epoch = 'latest'

[contracts.certificate-manager-v1]
path = 'contracts/certificate-manager-v1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.registry]
path = 'contracts/registry.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
